##########################################################
# application.yaml   (used for development purposes)
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080
###########################################################
# Database Settings
##########################################################
app.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/app1_db
  username: app1_user
  password: ENC(ywjaGwivmjYuwYCwiCskXg==)
  maxPoolSize: 10

development.mode: TrUe
network.name: NIPR
elasticSearch.url: http://localhost:9201

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: 'ab5823423464j1k2#><!!6298<-+'


spring:
  profiles:
    active: dev



---
#Dev Profile

spring:
  profiles: dev

network.name: NIPR
hdfs.enabled: false
show.classified.banner: false


---
#Test Profile

spring:
  profiles: test

network.name: SIPR
hdfs.enabled: true
show.classified.banner: true
